-- ============================================================================
-- DanceHub - initial schema
--
-- Mirrors the JPA entities under com.dncehub.entity as of this migration.
-- Types are chosen to satisfy `spring.jpa.hibernate.ddl-auto: validate`:
-- Hibernate checks table + column presence and JDBC type, so the definitions
-- below must stay in step with the entities whenever those change.
-- ============================================================================

-- ---------------------------------------------------------------- users -----
CREATE TABLE users (
    id             UUID         NOT NULL,
    email          VARCHAR(255) NOT NULL,
    full_name      VARCHAR(255) NOT NULL,
    -- NULL for OAuth2-only users, who never set a password
    password       VARCHAR(255),
    role           VARCHAR(255) NOT NULL,
    account_status VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ------------------------------------------------------- refresh_tokens -----
CREATE TABLE refresh_tokens (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    token      VARCHAR(512) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    user_id    UUID         NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- --------------------------------------------------- instructor_profiles ----
CREATE TABLE instructor_profiles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          UUID   NOT NULL,
    experience_years INTEGER,
    -- comma-separated, e.g. Salsa,Bachata,Hip-Hop
    dance_styles     VARCHAR(255),
    hourly_rate      NUMERIC(10, 2),
    city             VARCHAR(255),
    teaching_mode    VARCHAR(255),
    CONSTRAINT pk_instructor_profiles PRIMARY KEY (id),
    CONSTRAINT uq_instructor_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_instructor_profiles_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- matches findByCityIgnoreCase, which Spring Data renders as UPPER(city) = UPPER(?)
CREATE INDEX idx_instructor_profiles_city ON instructor_profiles (UPPER(city));

-- ------------------------------------------------------ student_profiles ----
CREATE TABLE student_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         UUID   NOT NULL,
    -- comma-separated, e.g. Salsa,Contemporary
    dance_interests VARCHAR(255),
    bio             TEXT,
    CONSTRAINT pk_student_profiles PRIMARY KEY (id),
    CONSTRAINT uq_student_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_student_profiles_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

-- ------------------------------------------------- saved_instructors (join) -
CREATE TABLE saved_instructors (
    student_id    BIGINT NOT NULL,
    instructor_id BIGINT NOT NULL,
    CONSTRAINT pk_saved_instructors PRIMARY KEY (student_id, instructor_id),
    CONSTRAINT fk_saved_instructors_student FOREIGN KEY (student_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_instructors_instructor FOREIGN KEY (instructor_id)
        REFERENCES instructor_profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_saved_instructors_instructor ON saved_instructors (instructor_id);

-- ---------------------------------------------------- availability_slots ----
CREATE TABLE availability_slots (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    instructor_id BIGINT       NOT NULL,
    slot_type     VARCHAR(255) NOT NULL,
    -- 1 = Monday .. 7 = Sunday; NULL when slot_type is ONE_TIME
    day_of_week   INTEGER,
    -- NULL when slot_type is RECURRING
    slot_date     DATE,
    start_time    TIME(6)      NOT NULL,
    end_time      TIME(6)      NOT NULL,
    available     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_availability_slots PRIMARY KEY (id),
    CONSTRAINT fk_availability_slots_instructor FOREIGN KEY (instructor_id)
        REFERENCES instructor_profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_availability_slots_instructor ON availability_slots (instructor_id);

-- -------------------------------------------------------------- bookings ----
CREATE TABLE bookings (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    student_id    BIGINT       NOT NULL,
    instructor_id BIGINT       NOT NULL,
    slot_id       BIGINT       NOT NULL,
    booking_date  DATE         NOT NULL,
    status        VARCHAR(255) NOT NULL,
    total_amount  NUMERIC(10, 2),
    -- STUDENT or INSTRUCTOR; populated only on cancellation
    cancelled_by  VARCHAR(255),
    version       BIGINT,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_bookings_student FOREIGN KEY (student_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_instructor FOREIGN KEY (instructor_id)
        REFERENCES instructor_profiles (id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_slot FOREIGN KEY (slot_id)
        REFERENCES availability_slots (id) ON DELETE CASCADE
);

CREATE INDEX idx_bookings_student     ON bookings (student_id, booking_date);
CREATE INDEX idx_bookings_instructor  ON bookings (instructor_id, booking_date);
-- serves the double-booking guard (findActiveOnSlotAndDate)
CREATE INDEX idx_bookings_slot_date   ON bookings (slot_id, booking_date);
-- serves the auto-complete sweep (findPastActive)
CREATE INDEX idx_bookings_date_status ON bookings (booking_date, status);

-- ------------------------------------------------------------- workshops ----
CREATE TABLE workshops (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    instructor_id    BIGINT         NOT NULL,
    title            VARCHAR(255)   NOT NULL,
    description      TEXT,
    dance_style      VARCHAR(255),
    poster_url       VARCHAR(255),
    venue            VARCHAR(255),
    city             VARCHAR(255),
    online           BOOLEAN        NOT NULL DEFAULT FALSE,
    meeting_link     VARCHAR(255),
    workshop_date    DATE           NOT NULL,
    start_time       TIME(6)        NOT NULL,
    end_time         TIME(6)        NOT NULL,
    price            NUMERIC(10, 2) NOT NULL,
    total_seats      INTEGER        NOT NULL,
    registered_seats INTEGER        NOT NULL DEFAULT 0,
    status           VARCHAR(255)   NOT NULL,
    version          BIGINT,
    created_at       TIMESTAMP(6),
    CONSTRAINT pk_workshops PRIMARY KEY (id),
    CONSTRAINT fk_workshops_instructor FOREIGN KEY (instructor_id)
        REFERENCES instructor_profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_workshops_instructor  ON workshops (instructor_id);
-- serves fetchUpcoming / fetchUpcomingBy* and the stale-status sweep
CREATE INDEX idx_workshops_status_date ON workshops (status, workshop_date);

-- ------------------------------------------------ workshop_registrations ----
CREATE TABLE workshop_registrations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    workshop_id    BIGINT NOT NULL,
    student_id     BIGINT NOT NULL,
    -- PENDING, PAID or REFUNDED
    payment_status VARCHAR(255),
    registered_at  TIMESTAMP(6),
    CONSTRAINT pk_workshop_registrations PRIMARY KEY (id),
    -- backs existsByWorkshopIdAndStudentId, and blocks a concurrent double-register
    CONSTRAINT uq_workshop_registrations_workshop_student UNIQUE (workshop_id, student_id),
    CONSTRAINT fk_workshop_registrations_workshop FOREIGN KEY (workshop_id)
        REFERENCES workshops (id) ON DELETE CASCADE,
    CONSTRAINT fk_workshop_registrations_student FOREIGN KEY (student_id)
        REFERENCES student_profiles (id) ON DELETE CASCADE
);

CREATE INDEX idx_workshop_registrations_student ON workshop_registrations (student_id);
