server:
  port: 8080

spring:
  application:
    name: dncehub-backend
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
